### ISSUE TITLE
crash on plumb-opening a file

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#111]
Use plumb to open a file, see crash:

goroutine 28 [running, locked to thread]:
main.(*Text).fill(0xc00032ec18, 0x1649260, 0xc0008f2000)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:529 +0x1bf
main.(*Text).Redraw(0xc00032ec18, 0x488, 0x267, 0x63f, 0x291, 0x1cb, 0x300)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:151 +0x175
main.(*Text).Resize(0xc00032ec18, 0x474, 0x267, 0x63f, 0x291, 0x1, 0x474)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:177 +0x1ad
main.(*Window).Resize(0xc00032ec00, 0x474, 0x267, 0x63f, 0x3c2, 0x101, 0x36)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:264 +0x59a
main.(*Window).SetTag1(0xc00032ec00)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:550 +0x6d4
main.(*Window).SetTag(0xc00032ec00)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:463 +0x8c
main.(*Window).SetName(0xc00032ec00, 0xc00042c3f0, 0x2b)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:412 +0xf8
main.openfile(0x0, 0xc0000ba3f0, 0x4)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/look.go:738 +0xb9
main.plumblook(0xc0003f9e60)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/look.go:237 +0x10f
main.mousethread(0xc0000ca0c0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:308 +0x248
created by main.main
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:173 +0x8f9

**Comment by rjkroege** [comment]
I had this happen again. Possible insight: if the column that is the destination of the new window is empty (i.e. contains no windows) then that's when the crash happens.
