### ISSUE TITLE
Crash when typing in empty tag

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#151]
I accidentally deleted everything from the tag. (Foolish me, I wish undo worked in tags..)

I typed and things were sad.

```
Text.Select: DoubleClick returned 0, 59
panic: runtime error: index out of range

goroutine 68 [running]:
main.(*Window).Commit(0xc000497400, 0xc000497418)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:580 +0x2c1
main.(*Window).SetTag1(0xc000497400)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:493 +0x5a
main.(*Window).SetTag(0xc000497400)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:476 +0x8c
main.cut(0xc000497418, 0xc000497418, 0x0, 0x101, 0x0, 0x0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/exec.go:323 +0x5a0
main.(*Text).Type(0xc000497418, 0xc000000044)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:922 +0x230
main.(*Window).Type(0xc000497400, 0xc000497418, 0x44)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:431 +0x37
main.(*Row).Type(0x1373c00, 0xc000000044, 0x529, 0x16c, 0xc000497401)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/row.go:288 +0x133
main.keyboardthread(0xc0000c20c0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:468 +0x1c3
created by main.main
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:173 +0x921
```

**Comment by fhs** [comment]
I think Undo in tag works after https://github.com/rjkroege/edwood/commit/bfd2606a2e4e806d04db1aa53d740da6852e2baf ?

I'll send a PR for the crash soon.
