### ISSUE TITLE
crash when right-selecting

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#153]
Select a string with RMB in a tag. Watch the failure:

```
panic: runtime error: index out of range

goroutine 19 [running, locked to thread]:
main.(*Buffer).ReadC(...)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/buf.go:48
main.(*Text).ReadC(...)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:1292
main.expandfile(0xc0004a4418, 0x65, 0x6d, 0xc00027d990, 0x70)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/look.go:554 +0xe40
main.expand(0xc0004a4418, 0x65, 0x6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/look.go:637 +0x12d
main.look3(0xc0004a4418, 0x65, 0x6d, 0xc0004a4400)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/look.go:82 +0xc8
main.MovedMouse(0x41, 0x5a3, 0x4, 0xc2204545)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:439 +0x415
main.mousethread(0xc0000da0c0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:300 +0x2c4
created by main.main
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:172 +0x8fc
```

This happened twice in a row with a comparatively simple example so it should be possible to find a easy replication. The searched for string is at the end of a tag.

**Comment by cottagepainter** [comment]
This happens only in column tags and the edwood tag, not in window tags.

**Comment by rjkroege** [comment]
@cottagepainter: if you have repeatable replication instructions, can you add them here? I have a possible (as yet unpushed) fix.
