### ISSUE TITLE
elog ordering panic

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#177]
The following Edit command or a file `test.md`

```
Edit {
	,x/five/ c/10/
	e test.md
}
```

works (albeit with strange undo behaviour) in Acme. Conversely in Edwood, it's sad:

```
panic: Changes not in order

goroutine 68 [running]:
main.(*Elog).Delete(0xc000116648, 0x0, 0x599)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/elog.go:183 +0x28c
main.e_cmd(0xc000248928, 0xc0000b43c0, 0x200)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:248 +0x25f
main.cmdexec(0xc000248928, 0xc0000b43c0, 0x1)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:107 +0x379
main.cmdexec(0xc000248928, 0xc0000b43c0, 0x0)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:101 +0x233
main.editthread()
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:131 +0x42
created by main.editcmd
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:210 +0x19d
```

**Comment by rjkroege** [comment]
I also note in passing that `Edit e` behaviour on a mutated file is not the same as `Get` on a mutated file and the former is decidedly weird.

**Comment by rjkroege** [comment]
Got something similar with an attempt at a more complicated `Edit` op:
```
Untested: main.run(0xc0003c8a80, 0xc0002a78f0, 0x4, 0xc000af0700, 0x3a, 0x1, 0x0, 0x0, 0x0, 0x0, ...): /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/exec.go:667 +0x34
panic: Changes not in order

goroutine 1112 [running]:
main.(*Elog).Insert(0xc000b54828, 0x27e6, 0xc00028abf0, 0x3, 0x20)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/elog.go:151 +0x4b0
main.appendx(0xc000b547e0, 0xc000358780, 0x27e6, 0xc0007e6150)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:664 +0xdc
main.i_cmd(0xc0003c8b88, 0xc000358780, 0x27e6)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:294 +0x45
main.cmdexec(0xc0003c8b88, 0xc000358780, 0x10)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:108 +0x37a
main.loopcmd(0xc000b547e0, 0xc000358780, 0xc0004e75d0, 0x1, 0x1)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:712 +0x89
main.looper(0xc000b547e0, 0xc000358730, 0xc0007e6001)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:753 +0x1bc
main.x_cmd(0xc0003c8b88, 0xc000358730, 0x27eb)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:451 +0x49
main.cmdexec(0xc0003c8b88, 0xc000358730, 0x116ed01)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:108 +0x37a
main.cmdexec(0xc0003c8b88, 0xc000358730, 0xc0003585f0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:102 +0x230
main.editthread(0xc0001abcc0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:153 +0xbd
created by main.editcmd
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:223 +0x1be

**Comment by rjkroege** [comment]
Maybe I should fix the "Untested..."

**Comment by fhs** [comment]
`Untested` can be removed IMO because we have code coverage.

**Comment by rjkroege** [comment]
Conceivably this is a duplicate of #236. They are at least deeply related. Consider this bug to mean "don't crash if the user tried to run bad sam commands" and #236 to be "support running multiple commands as described there".
