### ISSUE TITLE
Deadlock between mousethread and xfidwrite

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#188]
I've been running into this issue once every few days. I suspect it might be triggered by the [Watch](https://github.com/eaburns/Watch/) command.

The relevant stack trace is below. This is what's happening:
```
xfidwrite(x):
	// acquire window lock (w=0xc00030ac00)
	xfideventwrite(x, w):
		row.lk.Lock() // blocks because mousethread has the lock

mousethread:
	MovedMouse:
		row.lk.Lock()
		// mousetext.w was previously set to 0xc00030ac00
		mousetext.w.Lock('M') // blocks because xfidwrite has the lock
```

```
goroutine 40 [semacquire, locked to thread]:
sync.runtime_SemacquireMutex(0xc00030ac0c, 0xc000224700)
        /home/big/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc00030ac08)
        /home/big/go/src/sync/mutex.go:134 +0xff
main.(*Window).Lock(0xc00030ac00, 0x4d)
        /home/fhs/go/src/github.com/rjkroege/edwood/wind.go:333 +0x35
main.MovedMouse(0x5c4, 0xde, 0x0, 0x7601c6b8)
        /home/fhs/go/src/github.com/rjkroege/edwood/acme.go:328 +0x70f
main.mousethread(0xc0000ae0c0)
        /home/fhs/go/src/github.com/rjkroege/edwood/acme.go:290 +0x2bb
created by main.main
        /home/fhs/go/src/github.com/rjkroege/edwood/acme.go:162 +0x936

goroutine 68 [semacquire]:
sync.runtime_SemacquireMutex(0x7982ec, 0x0)
        /home/big/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x7982e8)
        /home/big/go/src/sync/mutex.go:134 +0xff
main.xfideventwrite(0xc00014c840, 0xc00030ac00)
        /home/fhs/go/src/github.com/rjkroege/edwood/xfid.go:814 +0x2bc
main.xfidwrite(0xc00014c840)
        /home/fhs/go/src/github.com/rjkroege/edwood/xfid.go:584 +0xb71
main.xfidctl(0xc00014c840, 0xc0000ae0c0)
        /home/fhs/go/src/github.com/rjkroege/edwood/xfid.go:48 +0x9c
created by main.xfidallocthread
        /home/fhs/go/src/github.com/rjkroege/edwood/acme.go:616 +0x1c7
```

**Comment by rjkroege** [comment]
oh dear.

**Comment by rjkroege** [comment]
How are you running the watch command.

**Comment by fhs** [comment]
For Edwood, I run a script using Watch that runs all tests and generates coverage report. This is the script:
```sh
#!/bin/sh
set -e
unset DISPLAY
go test -covermode=atomic -coverprofile=c.out "$@"
go tool cover -html=c.out -o c.html
```
Anyway, I was able to reproduce the deadlock by running just `Watch date` after I put a 5 seconds sleep before the `row.lk.Lock()` line in `xfideventwrite`. You may need to move your mouse around a bit after you execute the command.

I'm surprised I never ran into the deadlock in acme, when the locking code is identical to Edwood. I'm guessing Edwood is just a bit slower.

**Comment by rjkroege** [comment]
FWIW: the locking code diverged quite a bit as Edwood admits more goroutines than Acme has LWPs. Thanks for the repro case. I'll take a look at this.
