### ISSUE TITLE
dump file internal package

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#206]
Load crashes when loading the dump file below. I think we should split off dump file parsing/marshaling to an internal package for easier testing.
```
/home/fhs
/lib/font/bit/lucsans/euro.8.font
/lib/font/bit/lucm/unicode.9.font
  0.0000000  59.9609375
w Newcol Kill Putall Dump Exit 
c          0 New Cut Paste Snarf Sort Zerox Delcol 
c          1 New Cut Paste Snarf Sort Zerox Delcol 
```
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*Row).loadimpl(0x7a0180, 0x7ffc80e26510, 0x15, 0xc0000b2701, 0x0, 0x0)
	/home/fhs/go/src/github.com/rjkroege/edwood/row.go:743 +0x1c63
main.(*Row).Load(0x7a0180, 0x7ffc80e26510, 0x15, 0x401, 0x300, 0xc0000c60c0)
	/home/fhs/go/src/github.com/rjkroege/edwood/row.go:622 +0x4c
main.main.func1(0x7bb758)
	/home/fhs/go/src/github.com/rjkroege/edwood/acme.go:123 +0x9bd
github.com/rjkroege/edwood/internal/draw.Main(...)
	/home/fhs/go/src/github.com/rjkroege/edwood/internal/draw/9fans.go:49
main.main()
	/home/fhs/go/src/github.com/rjkroege/edwood/acme.go:82 +0x27f
```

**Comment by fhs** [comment]
I started working on this. I think we can just use json and stop worrying about parsing issues?

**Comment by rjkroege** [comment]
Yes. Let's use JSON.
