### ISSUE TITLE
Crash while reading from xdata

### ISSUE THREAD

**Issue by fhs** [rjkroege/edwood#255]
This is very much reproducible: ~~read from `xdata` with negative `q0`~~. (see below)

```
panic: runtime error: slice bounds out of range [-2:]

goroutine 51 [running]:
panic(0x634ce0, 0xc000016960)
        /home/big/go/src/runtime/panic.go:706 +0x2c2 fp=0xc0001f7dd0 sp=0xc0001f7d40 pc=0x42ea42
runtime.goPanicSliceB(0xfffffffffffffffe, 0x2)
        /home/big/go/src/runtime/panic.go:87 +0xa3 fp=0xc0001f7e18 sp=0xc0001f7dd0 pc=0x42d543
main.xfidruneread(0xc0000c2000, 0xc00011a118, 0xcb0, 0xcb2, 0xc0001f7f30)
        /home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20190628123847-c80f7ecdf670/xfid.go:944 +0x397 fp=0xc0001f7ec8 sp=0xc0001f7e18 pc=0x5d43d7
main.xfidread(0xc0000c2000)
        /home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20190628123847-c80f7ecdf670/xfid.go:372 +0x9ba fp=0xc0001f7f88 sp=0xc0001f7ec8 pc=0x5d117a
main.xfidctl(0xc0000c2000, 0x69f500, 0xc000010120)
        /home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20190628123847-c80f7ecdf670/xfid.go:52 +0x9c fp=0xc0001f7fc8 sp=0xc0001f7f88 pc=0x5cf68c
runtime.goexit()
        /home/big/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001f7fd0 sp=0xc0001f7fc8 pc=0x45bff1
created by main.xfidallocthread
        /home/fhs/go/pkg/mod/github.com/rjkroege/edwood@v0.2.1-0.20190628123847-c80f7ecdf670/acme.go:619 +0x1d4
```

**Comment by fhs** [comment]
Correction: maybe not negative `q0`, but I can reproduce it with [`acme-lsp`](https://github.com/fhs/acme-lsp) with the `L win auto` command. I'll investigate.
