### ISSUE TITLE
crashing on start in big sur

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#311]
On MacOS Big Sur (beta 7), intermittent crashes on start:

```
panic: runtime error: index out of range [10] with length 10

goroutine 66 [running, locked to thread]:main.(*Column).Grow(0xc0000d6000, 0xc000271000, 0x1)
	/Users/rjkroege/tools/edwood/col.go:456 +0x1138
main.(*Text).Show(0xc000271120, 0xd8, 0x6b2, 0x501)
	/Users/rjkroege/tools/edwood/text.go:1205 +0x385
main.flushwarnings()
	/Users/rjkroege/tools/edwood/util.go:289 +0x194
main.mousethread(0x159d900, 0xc00011a1e0)
	/Users/rjkroege/tools/edwood/acme.go:304 +0x59
created by main.main.func2
	/Users/rjkroege/tools/edwood/acme.go:186 +0x82a
```

**Comment by rjkroege** [comment]
That looks like a race condition to me.

**Comment by fhs** [comment]
Possibly related to #265?

**Comment by rjkroege** [comment]
After investigating: I think that this bug is exposed by #312: the `win` session starts from a dump file, promptly dies, is removed during the execution of the loop in `Column.Grow`.

**Comment by rjkroege** [comment]
I was wrong. It's more likely to be flushing a warning *while* continuing to reconstitute a dump file.

**Comment by rjkroege** [comment]
Both this and #265 are probably related. There's a general need for Edwood to be more principled about row and window concurrency control.

**Comment by rjkroege** [comment]
I'm sure that this is not BigSur specific. I think that it's related to attempting to load `dump` files with a certain invalid configuration.
