### ISSUE TITLE
lock sadness

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#36]
I middle click on `go build` in the tag of a `.../edwood` and got the following sadness:

The full stack trace was very long. We leak go routines in exec somewhere...

```
Untested: main.execute(0xc420045c18, 0x59, 0x59, 0x0, 0x0): /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/exec.go:121 +0x37
q1 == q0
selection chosen
Full path is /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood
Untested: main.run(0xc420045c00, 0xc420210110, 0xa, 0xc42046fa40, 0x3a, 0x1, 0x0, 0x0, 0x0, 0x0, ...): /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/exec.go:637 +0x34
fatal error: sync: unlock of unlocked mutex
goroutine 22 [running]:
runtime.throw(0x11e484c, 0x1e)
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:616 +0x81 fp=0xc420054e90 sp=0xc420054e70 pc=0x102a0f1
sync.throw(0x11e484c, 0x1e)
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:605 +0x35 fp=0xc420054eb0 sp=0xc420054e90 pc=0x102a065
sync.(*Mutex).Unlock(0x12dc220)
        /usr/local/Cellar/go/1.10.1/libexec/src/sync/mutex.go:184 +0xc2 fp=0xc420054ed8 sp=0xc420054eb0 pc=0x10680d2
main.fsysdelid(0xc4202ba180)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/fsys.go:191 +0x1b2 fp=0xc420054f40 sp=0xc420054ed8 pc=0x1157002
...
```

**Comment by paul-lalonde** [comment]
Fixed in ed2c46d0d56623fdd480dbe1249cf80184b1c872  I thought I'd pushed this earlier, but here it is.
