### ISSUE TITLE
Crashing on start in Ubuntu 20 LTS

### ISSUE THREAD

**Issue by juanfgarcia** [rjkroege/edwood#361]
I've installed with:

`go get -u -tags 'duitdraw mux9p' github.com/rjkroege/edwood`

And when I execute edwood I get this trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f1032]

goroutine 38 [running]:
github.com/fhs/mux9p.ListenContext(0x709ef0, 0xc000128018, 0x6b8b46, 0x4, 0xc0000900e0, 0x1b, 0x7f84a0006008, 0xc0000dc000, 0x0, 0x0, ...)
	/home/juanfgarcia/go/pkg/mod/github.com/fhs/mux9p@v0.3.1/mux9p.go:102 +0x52
github.com/fhs/mux9p.Listen(...)
	/home/juanfgarcia/go/pkg/mod/github.com/fhs/mux9p@v0.3.1/mux9p.go:97
main.post9pservice.func1(0xc0000900e0, 0x1b, 0x70bff0, 0xc0000dc000)
	/home/juanfgarcia/go/pkg/mod/github.com/rjkroege/edwood@v0.2.0/fsys_unix.go:32 +0xc5
created by main.post9pservice
	/home/juanfgarcia/go/pkg/mod/github.com/rjkroege/edwood@v0.2.0/fsys_unix.go:31 +0x125
```

The plan9port acme is working in that same machine.

I hope this don't duplicate #311 as the error message is different.

**Comment by fhs** [comment]
Try the master branch. Version `v0.2.0` is more than two years old at this point.
```
go install -tags 'duitdraw mux9p' github.com/rjkroege/edwood@master
```
@rjkroege Maybe a new version should be tagged?

**Comment by rjkroege** [comment]
Yes. Time for a new release. In the interim. please just use HEAD. 😀

**Comment by rjkroege** [comment]
@juanfgarcia I made a new release. I'd expect it to work. Please give it a whirl and re-open if it's not working.
