### ISSUE TITLE
Crash when double-clicking

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#41]
Double clicking caused this crash. The offsets seem suspicious.

```
Text.Select: DoubleClick returned 3067, 3075
panic: acme: textsetselect p0=903 p1=0 q0=3081 q1=0 t.org=0 nchars=903
goroutine 35 [running, locked to thread]:
main.(*Text).SetSelect(0xc4201aad28, 0xc09, 0x0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:1308 +0x352
main.(*Text).Select(0xc4201aad28)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:1195 +0x4cc
main.MovedMouse(0x104, 0x1a2, 0x1, 0xa56f001d)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:418 +0x4fb
main.mousethread(0xc4200b60c0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:297 +0x31c
created by main.main
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:171 +0x934
```

**Comment by paul-lalonde** [comment]
This call stack is from the "left button down after trying an action and now dancing on the other two buttons" code path - paste, unpaste, cancel stuff.  I've been dancing on it and can't reproduce.  I suspect one of my fixes clicked extents has fixed this.  I'll keep my eyes open for reproducers here.
