### ISSUE TITLE
Edit D command issues

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#53]
I opened many files in Edwood. See a different for bug for how file management got to be painful. I attempted to close them `Edit X/\.(go)$/ D` and it didn't work. This makes sense because `D` isn't implemented?

But it also crashed:

```
Unimplemented: main.D_cmd(0xc4202ad528, 0xc4203c80f0, 0x0): /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/ecmd.go:204 +0x20
cmdstartp= [10]
Collecttoken=
goroutine 43 [running]:
runtime/debug.Stack(0x10, 0x0, 0x0)
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/debug/stack.go:16 +0x22
main.atnl()
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:325 +0x61
main.collecttoken(0x12d612c, 0x1, 0x1, 0x0, 0x0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:383 +0x356
main.parsecmd(0x0, 0xc4201023c0)
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:515 +0x477
main.editthread()
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:145 +0x7f
created by main.editcmd
        /Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/edit.go:231 +0x1d6
cmdstartp= [10]
```

Aside: there were more go routines with the same stack dump that crashed at the same time.

**Comment by fhs** [comment]
I think the crash was fixed by a0d6ffdeb34a23ba6fff70a452a14d27a0df4143, which made `editerror` properly terminate the goroutine. I can't reproduce it anymore.
