### ISSUE TITLE
crash while deleting text at end of text

### ISSUE THREAD

**Issue by rjkroege** [rjkroege/edwood#6]
oops.

```
panic: runtime error: index out of range

goroutine 11 [running]:
github.com/rjkroege/edwood/frame.(*Frame).Delete(0xc4201a4fc0, 0x237, 0x238, 0x5d4)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/frame/delete.go:51 +0xdd2
main.(*Text).Delete(0xc420477d20, 0x237, 0x238, 0x0)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:608 +0x3a8
main.(*Text).Type(0xc420477d20, 0xc400000008)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/text.go:942 +0x8bb
main.(*Window).Type(0xc420477c00, 0xc420477d20, 0x8)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/wind.go:392 +0x37
main.(*Row).Type(0x12cde00, 0x8, 0x256, 0x3b6, 0x1)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/row.go:277 +0x139
main.keyboardthread(0xc4200ce0c0)
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:456 +0x274
created by main.main
	/Users/rjkroege/tools/gopkg/src/github.com/rjkroege/edwood/acme.go:181 +0x907
```

Note to self... Hit `Put` way more frequently.

**Comment by rjkroege** [comment]
I was editing and hit some combination of enter / delete keys. And ka-bam. Conceivably we need a scheme to better report / log failures.
